name: Node.js Advisory Board
description: "Moving Node.js Forward"
url: http://www.nodeadvisoryboard.com
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
markdown: redcarpet
highlighter: pygments
next_meeting: April 24, 2015 6PM EDT / 3PM PDT
next_meeting_stamp: 2015-4-24
