name: Node.js Advisory Board
description: "Moving Node.js Forward"
url: http://www.nodeadvisoryboard.com
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
markdown: redcarpet
highlighter: pygments
next_meeting: June 15, 2015 5PM EDT / 2PM PDT
next_meeting_stamp: 2015-6-15
